import type { Metadata } from "next";
import type { ReactNode } from "react";

import { fonts } from "@/components/fonts";

import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  readonly children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(fonts, "relative min-h-screen")}>{children}</body>
    </html>
  );
}
